swagger: "2.0"
info:
  description: "Food delivery API"
  version: "0.1.0"
  title: "Food delivery"
host: "127.0.0.1:8080"
basePath: "/api"
tags:
- name: "food_delivery"
  description: "Operations about food delivery"
schemes:
- "https"
- "http"
paths:
  /dishes:
    post:
      tags:
      - "dish"
      summary: "Create dish"
      description: "This can only be done by the logged in user."
      operationId: "createDish"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Dish object that should be created"
        required: true
        schema:
          $ref: "#/definitions/NewDish"
      responses:
        201:
          description: "Dish successfully create"
          schema: 
            $ref: "#/definitions/CreatedDish"
        400:
          description: "Data is invalid"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ErrorResponse"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
  
definitions:
  NewDish:
    type: "object"
    required: 
    - "mainDishInfo"
    - "dishType"
    - "dishCalories"
    - "dishCookingTimeMinutes"
    properties:
      mainDishInfo:
        type: object
        properties:
          dishName:
            type: "string"
            minLength: 1
            maxLength: 64
            example: "Lasagna"
          dishPrice:
            type: "integer"
            format: "int64"
            minimum: 1
            example: 250
      dishType:
        type: "string"
        enum:
        - DRINK
        - MAIN
        - SALAD
        - SANDWICH
        - BURGER
        - DESSERT
        - PIZZA
        - SUSHI
        - BAKERY
        example: "MAIN"
      dishCalories:
        type: "integer"
        format: "int64"
        minimum: 1
        example: 175
      dishCookingTimeMinutes:
        type: "integer"
        format: "int64"
        minimum: 1
        example: 30
  CreatedDish:
    type: object
    properties:
      id:
        type: "integer"
        format: "int64"
        minimum: 1
      mainDishInfo:
        type: object
        properties:
          dishName:
            type: "string"
            minLength: 1
            maxLength: 64
            example: "Lasagna"
          dishPrice:
            type: "integer"
            format: "int64"
            minimum: 1
      dishType:
        type: "string"
        enum:
        - DRINK
        - MAIN
        - SALAD
        - SANDWICH
        - BURGER
        - DESSERT
        - PIZZA
        - SUSHI
        - BAKERY
        example: "ADMIN"
      dishCalories:
        type: "integer"
        format: "int64"
        minimum: 1
      dishCookingTimeMinutes:
        type: "integer"
        format: "int64"
        minimum: 1
        example: 30
  ErrorResponse:
    type: "object"
    properties:
      code:
        type: "string"
      description:
        type: "string"
      payload:
        type: "object"
