server:
  servlet:
    context-path: /api
spring:
  liquibase:
    change-log: classpath*:migrations/master-changelog.yaml
    user: postgres
    url: jdbc:postgresql://rds-postgres-delivery.cqulanj8rndz.eu-central-1.rds.amazonaws.com:5432/delivery
  datasource:
    url: jdbc:postgresql://rds-postgres-delivery.cqulanj8rndz.eu-central-1.rds.amazonaws.com:5432/delivery
    username: postgres
    password: customVITAroot
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: ru.relex.delivery.db.handler
cloud:
  aws:
    credentials:
      accessKey: AKIASGKEBJAWTYAN6DFG
      secretKey: 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
    region: eu-central-1
    s3:
      bucket: dovecote-bucket-97
      endpointUrl: https://s3.eu-central-1.amazonaws.com
